CREATE TABLE `config_meta` comment '配置元信息表'(
  `id` BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY COMMENT '自增主键',
  `app_id` VARCHAR(64) DEFAULT NOT NULL COMMENT '应用id',
  `code` VARCHAR(64) DEFAULT NOT NULL COMMENT '编码',
  `property` VARCHAR(64) DEFAULT NOT NULL COMMENT '属性名',
  `column_name` VARCHAR(64) DEFAULT NOT NULL COMMENT '列名',
  `description` VARCHAR(128) DEFAULT '' COMMENT '说明',
  `sort` INT DEFAULT '0' COMMENT '排序',
  `gmt_create` TIMESTAMP DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
  `gmt_modified` TIMESTAMP DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP() COMMENT '修改时间'
);

CREATE TABLE `config_item` COMMENT '配置条目表'(
  `id` BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY COMMENT '自增主键',
  `app_id` VARCHAR(64) DEFAULT NOT NULL COMMENT '应用id',
  `meta_code` VARCHAR(64) DEFAULT NOT NULL COMMENT '配置元信息编码',
  `parent_id` BIGINT DEFAULT '0' COMMENT '父配置项id',
  `sort` INT DEFAULT '0' COMMENT '排序',
  `varchar1` VARCHAR(512) DEFAULT '' COMMENT '字符串1',
  `varchar2` VARCHAR(512) DEFAULT '' COMMENT '字符串2',
  `varchar3` VARCHAR(512) DEFAULT '' COMMENT '字符串3',
  `varchar4` VARCHAR(512) DEFAULT '' COMMENT '字符串4',
  `varchar5` VARCHAR(512) DEFAULT '' COMMENT '字符串5',
  `text1` CLOB DEFAULT NULL COMMENT '长文本1',
  `decimal1` DECIMAL(19,4) DEFAULT '0.0000' COMMENT '数字1',
  `datetime1` TIMESTAMP DEFAULT CURRENT_TIMESTAMP() COMMENT '日期1',
  `gmt_create` TIMESTAMP DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
  `gmt_modified` TIMESTAMP DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP() COMMENT '修改时间'
);


INSERT INTO `config_meta`(`app_id`, `code`, `property`, `column_name`, `description`, `sort`, `gmt_create`, `gmt_modified`) VALUES
('platform','userType','code','varchar1','类型编码',10,'2018-05-10 17:54:31','2018-05-10 21:14:08'),
('platform','userType','name','varchar2','类型名',20,'2018-05-10 17:54:31','2018-05-10 21:14:08'),
('platform','userType','description','varchar3','说明',30,'2018-05-10 17:54:31','2018-05-10 20:32:23'),
('platform','userType','img','varchar4','图标',40,'2018-05-10 17:54:31','2018-05-10 20:32:23');

INSERT INTO `config_item`(`app_id`, `meta_code`, `varchar1`, `varchar2`, `varchar3`, `varchar4`, `gmt_create`, `gmt_modified`) VALUES
('platform','userType','user','普通用户','刚注册还未认证用户','1.jpg','2018-05-10 17:54:31','2018-05-10 21:14:08'),
('platform','userType','member','会员','已认证用户','2.jpg','2018-05-10 17:54:31','2018-05-10 21:14:08'),
('platform','userType','VIP1','铜牌会员','铜牌会员','3.jpg','2018-05-10 17:54:31','2018-05-10 21:14:08'),
('platform','userType','VIP2','银牌会员','银牌会员','4.jpg','2018-05-10 17:54:31','2018-05-10 21:14:08'),
('platform','userType','VIP3','金牌会员','金牌会员','5.jpg','2018-05-10 17:54:31','2018-05-10 21:14:08'),
('platform','userType','VVIP','VVIP','VVIP','6.jpg','2018-05-10 17:54:31','2018-05-10 21:14:08');

